// <auto-generated />
using System;
using FoodApi.dbhelper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodApi.Migrations
{
    [DbContext(typeof(AppDB))]
    [Migration("20190210185522_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("FoodApi.dbhelper.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FoodApi.dbhelper.FridgeProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<int>("ProductId");

                    b.Property<string>("Status");

                    b.Property<decimal>("quantity");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("fridgeProducts");
                });

            modelBuilder.Entity("FoodApi.dbhelper.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryId");

                    b.Property<int>("ExpireDays");

                    b.Property<string>("Name");

                    b.Property<string>("NutritionDetails");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FoodApi.dbhelper.FridgeProduct", b =>
                {
                    b.HasOne("FoodApi.dbhelper.Product", "Product")
                        .WithMany("FridgeProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FoodApi.dbhelper.Product", b =>
                {
                    b.HasOne("FoodApi.dbhelper.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
